### PR TITLE
solc 0.5.x compatibility, ability to change compilers as needed

### LINKED ISSUE #63: Add support for solc 0.5.0
* `py-solc` Version: 3.2.0
* `solc` Version: 0.5.0
* Python Version: 3.6.7
* OS: linux

To keep up to date with the latest changes, it would be nice to have support for the latest solc version. On my machine that'd be `0.5.0+commit.1d4f565a.Linux.g++` - installed from the Ethereum PPA:
`deb http://ppa.launchpad.net/ethereum/ethereum/ubuntu bionic main`

Background: [Mythril](https://github.com/ConsenSys/mythril-classic) is using py-solc as a wrapper to provide various solc versions as the contracts to scan require it. Having an up-to-date wrapper greatly helps us to keep our code clean from hacky workarounds. :slightly_smiling_face: 

### What was wrong?
```
Traceback (most recent call last):
  File "/home/spoons/diligence/mythril-classic/myth", line 9, in <module>
    mythril.interfaces.cli.main()
  File "/home/spoons/diligence/mythril-classic/mythril/interfaces/cli.py", line 282, in main
    enable_online_lookup=args.query_signature,
  File "/home/spoons/diligence/mythril-classic/mythril/mythril.py", line 120, in __init__
    self.solc_binary = self._init_solc_binary(solv)
  File "/home/spoons/diligence/mythril-classic/mythril/mythril.py", line 245, in _init_solc_binary
    solc.install_solc("v" + version)
  File "/home/spoons/diligence/mythril-classic/.tox/py36/lib/python3.6/site-packages/solc/install.py", line 508, in install_solc
    ', '.join(sorted(INSTALL_FUNCTIONS[platform].keys())),
ValueError: Installation of solidity==v0.5.0 is not supported.  Must be one of v0.4.1, v0.4.11, v0.4.12, v0.4.13, v0.4.14, v0.4.15, v0.4.16, v0.4.17, v0.4.18, v0.4.19, v0.4.2, v0.4.20, v0.4.21, v0.4.22, v0.4.23, v0.4.24, v0.4.25, v0.4.6, v0.4.7, v0.4.8, v0.4.9
```

#### Cute Animal Picture

image

### LINKED ISSUE #64: py-solc is incompatible with Solidity compiler 0.5.0
* `py-solc` Version: 3.2.0
* `solc` Version: 0.5.0
* Python Version: 3.6.7
* OS:  Linux

### What was wrong?
py-solc is incompatible with Solidity compiler 0.5.0

`--combined-json clone-bin` is deprecated in version 0.5.0 but is set in main.py and wrapper.py. Has to be removed.

Compile from source uses the solc compiler option to compile from stdin but does this incorrectly.
The fix would be to add `command += "-" ` at the end of the command creation.
A quick and dirty fix for both issues can be seen on my repository master branch at:

https://github.com/Jonasmpi/py-solc

### PR DESCRIPTION
**Pull request by iamdefinitelyahuman**
### What was wrong?

* py-solc is incompatible with solc v0.5.0 due to depeciation of  "--combined-json clone-bin"
* solc v0.5.0 introduces many breaking changes and cannot compile v0.4.x contracts

Over the next few months, I'd imagine may of us will be working with contracts on both 0.4.x and 0.5.x simultaneously. To that end, it would be useful to be able to easily switch compiler versions.

### How was it fixed?

* Modified `wrapper.py` - line 87, added a check for version 0.5.x to remove the clone-bin argument if needed
* Modified `install.py` - can now install versions 0.5.0 and 0.5.1, and each version of solc is installed into `py-solc/bin/solc/`
* Added `main.set_solc_version` - modifies which compiler py-solc is actively using, and installs if necessary
* Added `main.get_installed_solc_versions` - to see which versions of solc have been installed
* Modified `__init__.py` so that on the first import it installs solc v0.5.1

fixes #63 
fixes #64 

#### Cute Animal Picture

baby llama approves

### CODE REVIEW

**Comment by pryce-turner** [comment]
Didn't see this one when I made mine. Fixes everything on my machine.

**Comment by iamdefinitelyahuman** [comment]
> Didn't see this one when I made mine. Fixes everything on my machine.

This PR is also failing the travis checks, and like you I'm not familiar with it's use.  I think the issue is because the tests are written assuming that solc is installed to /usr/bin but with how I've modified it, solc is now installed elsewhere.  Also this PR will need some more work to support windows users.  As suggested in the community guidelines, this is more meant to open a discussion as to whether this approach is one that's worth working on further.

**Comment by pryce-turner** [comment]
Yeah it looks like @pipermerriam and co are pretty busy over at web3.py getting it up to speed with Sol 0.5.x, hopefully the wrapper fixes are fairly easy and we can bring this up to spec soon as well. As far as I know, the clone-bin issue was the only _breaking_ change for the wrapper.

**Comment by kaisert** [comment]
Any updates on this?

**Comment by pipermerriam** [comment]
It's very likely that `py-solc` is going to be formally deprecated and no longer maintained in the very near term future.  It's an old carry-over from populus and wrapping solidity APIs like this has a large maintenance load that we can't justify.

**Comment by ritzdorf** [comment]
@pipermerriam Thanks for the update. Do you see any alternative to `py-solc`?

**Comment by pipermerriam** [comment]
Not that we plan to build/maintain but it should be quite trivial to fork this repository and maintain/update it yourself if it is an important part of your stack.

**Comment by iamdefinitelyahuman** [comment]
@pipermerriam thanks for letting us know, and for your work on this project to date.  I rely on `py-solc` a fair bit, so I will continue to maintain the repo I have forked and upload it to pypi under a similar name.

Update - my forked repo is now available on pypi:

`pip install py-solc-x`

**Pull request closed without merging**
